import streamlit as st
import requests
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fpdf import FPDF
from io import BytesIO
import re

st.set_page_config(page_title="LegalEase", page_icon="⚖️", layout="centered")


def sanitize_text(text: str) -> str:
    text = text.replace("**", "").replace("*", "").replace("#", "")
    text = text.replace("\u2018", "'").replace("\u2019", "'")
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    return text.strip()


def format_html_preview(text: str) -> str:
    paragraphs = text.split("\n")
    html = ""
    for p in paragraphs:
        if p.strip():
            html += f"<p style='margin-bottom:10px;'>{p}</p>"
    return html


def format_docx(text: str, doc_type: str) -> bytes:
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(11)
    title = doc.add_heading(doc_type, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for para in text.split("\n"):
        if para.strip():
            doc.add_paragraph(para)
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def format_pdf(text: str, doc_type: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, doc_type, ln=True, align="C")
    pdf.ln(5)
    pdf.set_font("Helvetica", size=11)
    for line in text.split("\n"):
        safe = line.encode("latin-1", "replace").decode("latin-1")
        pdf.multi_cell(0, 6, safe)
    pdf.ln(5)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Generated by LegalEase", ln=True, align="C")
    return pdf.output(dest="S").encode("latin-1")


st.title("⚖️ LegalEase")
st.markdown("<h4 style='text-align:center;'>AI-Powered Legal Document Generator</h4>",
            unsafe_allow_html=True)
st.markdown("---")

document_type = st.text_input("Document Type",
    placeholder="e.g., Freelance Work Contract")
parties = st.text_area("Parties Involved",
    placeholder="e.g., Jane Doe (Service Provider), TechNova Inc. (Client)")
terms = st.text_area("Terms & Conditions (use semicolons to separate points)",
    placeholder="e.g., Payment due within 30 days; Confidentiality required")
dates = st.text_input("Effective Date", placeholder="e.g., April 15, 2025")

if st.button("Generate Document"):
    if not document_type or not parties:
        st.warning("Please fill in at least the Document Type and Parties.")
    else:
        with st.spinner("Generating document... (may take 10-20 seconds)"):
            payload = {
                "document_type": document_type,
                "parties": parties,
                "terms": terms,
                "dates": dates
            }
            try:
                response = requests.post(
                    "http://localhost:8000/generate",
                    json=payload, timeout=120)
                result = response.json()
                generated_text = sanitize_text(
                    result.get("document", "No document returned."))
                st.session_state["generated_text"] = generated_text
                st.session_state["doc_type"] = document_type
                st.session_state["show_edit"] = False
                st.success("Document Generated Successfully!")
            except Exception as e:
                st.error(f"Error connecting to backend: {e}")

if "generated_text" in st.session_state:
    generated_text = st.session_state["generated_text"]
    doc_title = st.session_state.get("doc_type", "Legal Document")

    st.markdown("### 📄 Preview")
    styled_html = format_html_preview(generated_text)
    st.markdown(
        f"<div style='background:#1e1e1e; color:#f0f0f0; padding:20px; "
        f"border-radius:8px; max-height:400px; overflow-y:auto; "
        f"font-family:Georgia,serif; font-size:14px; line-height:1.6;'>"
        f"{styled_html}</div>",
        unsafe_allow_html=True
    )

    if st.button("✏️ Click to Edit Document"):
        st.session_state["show_edit"] = True

    if st.session_state.get("show_edit"):
        edited = st.text_area(
            "Edit Document Below:",
            value=generated_text,
            height=300,
            key="edit_area"
        )
        st.session_state["generated_text"] = edited
        generated_text = edited

    st.markdown("### 📥 Download Options")
    safe_name = re.sub(r"[^a-zA-Z0-9_\- ]", "", doc_title).replace(" ", "_")

    st.download_button(
        "📄 Download as .TXT",
        data=generated_text,
        file_name=f"{safe_name}.txt",
        mime="text/plain"
    )

    docx_bytes = format_docx(generated_text, doc_title)
    st.download_button(
        "📝 Download as .DOCX",
        data=docx_bytes,
        file_name=f"{safe_name}.docx",
        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )

    pdf_bytes = format_pdf(generated_text, doc_title)
    st.download_button(
        "📕 Download as .PDF",
        data=pdf_bytes,
        file_name=f"{safe_name}.pdf",
        mime="application/pdf"
    )